// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockKafkaSender creates a new instance of MockKafkaSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKafkaSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKafkaSender {
	mock := &MockKafkaSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKafkaSender is an autogenerated mock type for the KafkaSender type
type MockKafkaSender struct {
	mock.Mock
}

type MockKafkaSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKafkaSender) EXPECT() *MockKafkaSender_Expecter {
	return &MockKafkaSender_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type MockKafkaSender
func (_mock *MockKafkaSender) Send(ctx context.Context, chatID int64, url string, description string) error {
	ret := _mock.Called(ctx, chatID, url, description)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string) error); ok {
		r0 = returnFunc(ctx, chatID, url, description)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKafkaSender_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockKafkaSender_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - url string
//   - description string
func (_e *MockKafkaSender_Expecter) Send(ctx interface{}, chatID interface{}, url interface{}, description interface{}) *MockKafkaSender_Send_Call {
	return &MockKafkaSender_Send_Call{Call: _e.mock.On("Send", ctx, chatID, url, description)}
}

func (_c *MockKafkaSender_Send_Call) Run(run func(ctx context.Context, chatID int64, url string, description string)) *MockKafkaSender_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockKafkaSender_Send_Call) Return(err error) *MockKafkaSender_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKafkaSender_Send_Call) RunAndReturn(run func(ctx context.Context, chatID int64, url string, description string) error) *MockKafkaSender_Send_Call {
	_c.Call.Return(run)
	return _c
}
