// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/es-debug/backend-academy-2024-go-template/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// MockExternalClient is an autogenerated mock type for the ExternalClient type
type MockExternalClient struct {
	mock.Mock
}

type MockExternalClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExternalClient) EXPECT() *MockExternalClient_Expecter {
	return &MockExternalClient_Expecter{mock: &_m.Mock}
}

// RetrieveUpdates provides a mock function with given fields: ctx, link
func (_m *MockExternalClient) RetrieveUpdates(ctx context.Context, link string) ([]models.Update, error) {
	ret := _m.Called(ctx, link)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveUpdates")
	}

	var r0 []models.Update
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Update, error)); ok {
		return rf(ctx, link)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Update); ok {
		r0 = rf(ctx, link)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Update)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, link)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExternalClient_RetrieveUpdates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveUpdates'
type MockExternalClient_RetrieveUpdates_Call struct {
	*mock.Call
}

// RetrieveUpdates is a helper method to define mock.On call
//   - ctx context.Context
//   - link string
func (_e *MockExternalClient_Expecter) RetrieveUpdates(ctx interface{}, link interface{}) *MockExternalClient_RetrieveUpdates_Call {
	return &MockExternalClient_RetrieveUpdates_Call{Call: _e.mock.On("RetrieveUpdates", ctx, link)}
}

func (_c *MockExternalClient_RetrieveUpdates_Call) Run(run func(ctx context.Context, link string)) *MockExternalClient_RetrieveUpdates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockExternalClient_RetrieveUpdates_Call) Return(_a0 []models.Update, _a1 error) *MockExternalClient_RetrieveUpdates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExternalClient_RetrieveUpdates_Call) RunAndReturn(run func(context.Context, string) ([]models.Update, error)) *MockExternalClient_RetrieveUpdates_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExternalClient creates a new instance of MockExternalClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExternalClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExternalClient {
	mock := &MockExternalClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
