// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/segmentio/kafka-go"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDLQHandler creates a new instance of MockDLQHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDLQHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDLQHandler {
	mock := &MockDLQHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDLQHandler is an autogenerated mock type for the DLQHandler type
type MockDLQHandler struct {
	mock.Mock
}

type MockDLQHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDLQHandler) EXPECT() *MockDLQHandler_Expecter {
	return &MockDLQHandler_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type MockDLQHandler
func (_mock *MockDLQHandler) Send(ctx context.Context, msg kafka.Message, reason string) error {
	ret := _mock.Called(ctx, msg, reason)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, kafka.Message, string) error); ok {
		r0 = returnFunc(ctx, msg, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDLQHandler_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockDLQHandler_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - msg kafka.Message
//   - reason string
func (_e *MockDLQHandler_Expecter) Send(ctx interface{}, msg interface{}, reason interface{}) *MockDLQHandler_Send_Call {
	return &MockDLQHandler_Send_Call{Call: _e.mock.On("Send", ctx, msg, reason)}
}

func (_c *MockDLQHandler_Send_Call) Run(run func(ctx context.Context, msg kafka.Message, reason string)) *MockDLQHandler_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 kafka.Message
		if args[1] != nil {
			arg1 = args[1].(kafka.Message)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDLQHandler_Send_Call) Return(err error) *MockDLQHandler_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDLQHandler_Send_Call) RunAndReturn(run func(ctx context.Context, msg kafka.Message, reason string) error) *MockDLQHandler_Send_Call {
	_c.Call.Return(run)
	return _c
}
