// Code generated by mockery v2.53.2. DO NOT EDIT.

package botmocks

import (
	mock "github.com/stretchr/testify/mock"

	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
)

// MockTgAPI is an autogenerated mock type for the TgAPI type
type MockTgAPI struct {
	mock.Mock
}

type MockTgAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTgAPI) EXPECT() *MockTgAPI_Expecter {
	return &MockTgAPI_Expecter{mock: &_m.Mock}
}

// GetUpdatesChan provides a mock function with given fields: config
func (_m *MockTgAPI) GetUpdatesChan(config tgbotapi.UpdateConfig) tgbotapi.UpdatesChannel {
	ret := _m.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for GetUpdatesChan")
	}

	var r0 tgbotapi.UpdatesChannel
	if rf, ok := ret.Get(0).(func(tgbotapi.UpdateConfig) tgbotapi.UpdatesChannel); ok {
		r0 = rf(config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tgbotapi.UpdatesChannel)
		}
	}

	return r0
}

// MockTgAPI_GetUpdatesChan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpdatesChan'
type MockTgAPI_GetUpdatesChan_Call struct {
	*mock.Call
}

// GetUpdatesChan is a helper method to define mock.On call
//   - config tgbotapi.UpdateConfig
func (_e *MockTgAPI_Expecter) GetUpdatesChan(config interface{}) *MockTgAPI_GetUpdatesChan_Call {
	return &MockTgAPI_GetUpdatesChan_Call{Call: _e.mock.On("GetUpdatesChan", config)}
}

func (_c *MockTgAPI_GetUpdatesChan_Call) Run(run func(config tgbotapi.UpdateConfig)) *MockTgAPI_GetUpdatesChan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(tgbotapi.UpdateConfig))
	})
	return _c
}

func (_c *MockTgAPI_GetUpdatesChan_Call) Return(_a0 tgbotapi.UpdatesChannel) *MockTgAPI_GetUpdatesChan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTgAPI_GetUpdatesChan_Call) RunAndReturn(run func(tgbotapi.UpdateConfig) tgbotapi.UpdatesChannel) *MockTgAPI_GetUpdatesChan_Call {
	_c.Call.Return(run)
	return _c
}

// Request provides a mock function with given fields: c
func (_m *MockTgAPI) Request(c tgbotapi.Chattable) (*tgbotapi.APIResponse, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Request")
	}

	var r0 *tgbotapi.APIResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(tgbotapi.Chattable) (*tgbotapi.APIResponse, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(tgbotapi.Chattable) *tgbotapi.APIResponse); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tgbotapi.APIResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(tgbotapi.Chattable) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTgAPI_Request_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Request'
type MockTgAPI_Request_Call struct {
	*mock.Call
}

// Request is a helper method to define mock.On call
//   - c tgbotapi.Chattable
func (_e *MockTgAPI_Expecter) Request(c interface{}) *MockTgAPI_Request_Call {
	return &MockTgAPI_Request_Call{Call: _e.mock.On("Request", c)}
}

func (_c *MockTgAPI_Request_Call) Run(run func(c tgbotapi.Chattable)) *MockTgAPI_Request_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(tgbotapi.Chattable))
	})
	return _c
}

func (_c *MockTgAPI_Request_Call) Return(_a0 *tgbotapi.APIResponse, _a1 error) *MockTgAPI_Request_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTgAPI_Request_Call) RunAndReturn(run func(tgbotapi.Chattable) (*tgbotapi.APIResponse, error)) *MockTgAPI_Request_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: c
func (_m *MockTgAPI) Send(c tgbotapi.Chattable) (tgbotapi.Message, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 tgbotapi.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(tgbotapi.Chattable) (tgbotapi.Message, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(tgbotapi.Chattable) tgbotapi.Message); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(tgbotapi.Message)
	}

	if rf, ok := ret.Get(1).(func(tgbotapi.Chattable) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTgAPI_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockTgAPI_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - c tgbotapi.Chattable
func (_e *MockTgAPI_Expecter) Send(c interface{}) *MockTgAPI_Send_Call {
	return &MockTgAPI_Send_Call{Call: _e.mock.On("Send", c)}
}

func (_c *MockTgAPI_Send_Call) Run(run func(c tgbotapi.Chattable)) *MockTgAPI_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(tgbotapi.Chattable))
	})
	return _c
}

func (_c *MockTgAPI_Send_Call) Return(_a0 tgbotapi.Message, _a1 error) *MockTgAPI_Send_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTgAPI_Send_Call) RunAndReturn(run func(tgbotapi.Chattable) (tgbotapi.Message, error)) *MockTgAPI_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTgAPI creates a new instance of MockTgAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTgAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTgAPI {
	mock := &MockTgAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
