all: true
recursive: true
dir: "./mocks"
pkgname: "mocks"
filename: "mock_{{.SrcPackageName | lower}}_{{.InterfaceName | snakecase}}.go"
structname: "{{.Mock}}{{.InterfaceName}}"
formatter: "goimports"
log-level: "info"
template: "testify"
require-template-schema-exists: true
template-schema: "{{.Template}}.schema.json"
packages:
    github.com/es-debug/backend-academy-2024-go-template:
        config:
            all: true
