services:
    bot:
        build:
            context: ..
            dockerfile: ./docker/bot.Dockerfile
        ports:
            - "8081:8081"
        env_file:
            - ../.env
        network_mode: "host"
        restart: unless-stopped

    scrapper:
        build:
            context: ..
            dockerfile: ./docker/scrapper.Dockerfile
        ports:
            - "8080:8080"
        env_file: ../.env
        network_mode: "host"
        restart: unless-stopped
