serving:
    scrapperhost: scrapper
    bothost: bot
    scrapperport: 8080
    botport: 8081
database:
    access: orm
brokers:
    - host: kafka1
      port: 19092
    - host: kafka2
      port: 19093
cache:
    host: redis
    port: 6379
transport:
    mode: async
    topic: link.updates
    topicdlq: link.updates.dlq
    groupid: link.updates.1
notifier:
    numworkers: 16
updater:
    batchsize: 200
    numworkers: 16