serving:
    scrapperHost: scrapper
    botHost: bot
    scrapperPort: 8080
    botPort: 8081
    
database:
    access: orm
    
brokers:
    - host: kafka1
      port: 19092
    - host: kafka2
      port: 19093
      
cache:
    host: redis
    port: 6379
    
delivery:
    transport: kafka
    topic: link.updates
    dlqTopic: link.updates.dlq
    groupID: link.updates.1
    
notifier:
    numWorkers: 16
    
updater:
    batchSize: 200
    numWorkers: 16
    
timeouts:
    clientOverall: 10s
    serverRead: 5s
    serverWrite: 10s
    serverIdle: 60s

rateLimiter:
    TTL: 1hr
    maxPerSecond: 5.0
    burst: 10
    methods:
        - GET
        - POST
        - PUT
        - DELETE
    

retry:
    number: 5
    delay: 1s
    statusCodes:
        - 408
        - 429
        - 500
        - 502
        - 503
        - 504

circuitBreaker:
    maxRequests: 3
    interval: 0s
    timeout: 10s
    failureThreshold: 1
    